force-app/main/default/objects/Ids__c/Ids__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Id</label>
</CustomObject>

force-app/main/default/objects/Ids__c/fields/LeadDraftQueue__c.field-meta.xml
<CustomField>
    <fullName>LeadDraftQueue__c</fullName>
    <label>Lead - Draft Queue</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DraftSource__c.field-meta.xml
<CustomField>
    <fullName>DraftSource__c</fullName>
    <label>Draft Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/IsPartnerLead__c.field-meta.xml
<CustomField>
    <fullName>IsPartnerLead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Partner Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LeadsService.cls
public with sharing class LeadsService {

    /* public static void handleDraftLeadSourceBeforeInsert(Lead record) {
        if (isPartnerLead(record.DraftSource__c)) {
            record.IsPartnerLead__c = true;
            record.LeadSource = Label.LeadPartner;
            record.DraftSource__c = null;            
        } else {
            record.OwnerId = Ids__c.getOrgDefaults().LeadDraftQueue__c;
        }
    } */

    public static void handleDraftLeadSourceAfterInsert(Lead record, List<Lead> leadsToUpdate) {
        Lead l = new Lead();

        if (isPartnerLead(record.DraftSource__c)) {
            l.Id = record.Id;
            l.IsPartnerLead__c = true;
            l.LeadSource = Label.LeadPartner;
            l.DraftSource__c = null;            
        } else if (!record.OwnerId.equals(Ids__c.getOrgDefaults().LeadDraftQueue__c)) {
            l.Id = record.Id;
            l.OwnerId = Ids__c.getOrgDefaults().LeadDraftQueue__c;
        }

        if (String.isNotBlank(l.Id)) {
            leadsToUpdate.add(l);
        }        
    }


    public static void handleDraftLeadSourceAfterUpdate(Lead record, Lead oldRecord, List<Lead> leadsToUpdate) {
        Lead l = new Lead();

        if (isPartnerLead(record.DraftSource__c)) {
            l.Id = record.Id;
            l.IsPartnerLead__c = true;
            l.LeadSource = Label.LeadPartner;
            l.DraftSource__c = null;            
        } else if (!record.OwnerId.equals(Ids__c.getOrgDefaults().LeadDraftQueue__c)) {
            l.Id = record.Id;
            l.OwnerId = Ids__c.getOrgDefaults().LeadDraftQueue__c;
        }

        if (String.isNotBlank(l.Id)) {
            leadsToUpdate.add(l);
        }        
    }

    static Boolean isPartnerLead(String value) {
        return String.isNotBlank(value) ? value.contains(Label.LeadPartner) : false;
    }
}